export const chatCopy = {
  es: {
    closeHistory: 'Cerrar historial',
    title: 'Tu espacio de ayuda', subtitle: 'Una conversación. Todo más claro.',
    greeting: '¿En qué podemos ayudarte?', intro: 'Consulta sobre tus tarjetas y continúa a tu ritmo.',
    newChat: 'Nueva conversación', history: 'Tus conversaciones', empty: 'Tus chats aparecerán aquí.',
    session: 'Historial de esta sesión', sessionNote: 'El historial visible se limpia al salir o recargar. Las conversaciones permanecen en el servicio.',
    placeholder: 'Escribe tu consulta…', send: 'Enviar mensaje', back: 'Volver a mis tarjetas',
    assistant: 'Asistente', you: 'Tú', help: 'La ayuda que necesitas, en un solo lugar.',
    prompts: ['Consultar mis tarjetas', 'Tengo una duda sobre mi tarjeta', 'Necesito atención humana'],
    promptNote: 'Datos sintéticos · Las acciones requieren tu confirmación.',
    stub: 'Modo de prueba: respuestas limitadas, sin modelo de IA conectado.',
    support: 'Atención humana', transferred: 'Tu caso está en atención humana',
    transferNote: 'Puedes consultar su estado aquí. El chat directo con una persona todavía no está disponible.',
    refresh: 'Actualizar estado', messages: 'Mensajes de la conversación',
  },
  pt: {
    closeHistory: 'Fechar histórico',
    title: 'Seu espaço de ajuda', subtitle: 'Uma conversa. Tudo mais claro.',
    greeting: 'Como podemos ajudar?', intro: 'Consulte sobre seus cartões e continue no seu ritmo.',
    newChat: 'Nova conversa', history: 'Suas conversas', empty: 'Seus chats aparecerão aqui.',
    session: 'Histórico desta sessão', sessionNote: 'O histórico visível é limpo ao sair ou recarregar. As conversas permanecem no serviço.',
    placeholder: 'Escreva sua pergunta…', send: 'Enviar mensagem', back: 'Voltar aos meus cartões',
    assistant: 'Assistente', you: 'Você', help: 'A ajuda de que você precisa, em um só lugar.',
    prompts: ['Consultar meus cartões', 'Tenho uma dúvida sobre meu cartão', 'Preciso de atendimento humano'],
    promptNote: 'Dados sintéticos · As ações exigem sua confirmação.',
    stub: 'Modo de teste: respostas limitadas, sem modelo de IA conectado.',
    support: 'Atendimento humano', transferred: 'Seu caso está em atendimento humano',
    transferNote: 'Consulte o estado aqui. O chat direto com uma pessoa ainda não está disponível.',
    refresh: 'Atualizar estado', messages: 'Mensagens da conversa',
  },
}
